Create dotnet-desktop.yml
Finka95/CatNote pull request #15
Opened 2023-11-13 12:02 UTC by MaliyOna

2023-11-13 13:33 UTC, kalachck approved these changes

2023-11-13 15:18 UTC, nantonov requested changes

2023-11-13 15:18 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +        configuration: [Debug, Release]
Debug is not needed

2023-11-13 15:18 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +name: .NET Core Desktop
Why Core and why Desktop?

2023-11-13 15:18 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +        configuration: [Debug, Release]
And also, you don't use this configuration anywhere 
looks like it can be deleted

2023-11-13 15:18 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +    runs-on: windows-latest
Why not linux?

2023-11-13 15:18 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +      Solution_Name: CatNote.API.sln
Looks like you don't use this env vars

2023-11-13 15:18 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +      run: dotnet build --no-restore
You can specify configuration (like release) right here

2023-11-14 11:28 UTC, nantonov requested changes

2023-11-14 11:28 UTC, nantonov commented on .github/workflows/dotnet-desktop.yml
> +    # strategy:
Please, delete this commented code

2023-11-15 06:56 UTC, Genresal approved these changes

2023-11-15 09:02 UTC, nantonov approved these changes

2023-11-15 09:03 UTC, merged