Feature/nmd 468 create a function that allows achievements to be added to the user when their requirements are met
Finka95/CatNote pull request #20
Opened 2023-11-27 09:51 UTC by MaliyOna

I add tests, because my pipeline won`t work without them

2023-11-29 09:09 UTC, kalachck requested changes

2023-11-29 09:09 UTC, kalachck commented on CatNote.DAL/Repositories/TaskRepository.cs
> +using CatNote.DAL.Entities;
Unnecessary usings

2023-11-29 09:09 UTC, kalachck commented on CatNote.Domain/Enums/AchievementType.cs
> +    None,
Use explicit Enums

2023-11-29 09:09 UTC, kalachck commented on CatNote.IntegrationTests/TaskTests.cs
> +            UserId = userId
Remove data creation into separate class

2023-11-29 09:09 UTC, kalachck commented on CatNote.IntegrationTests/UserTests.cs
> +using System.Linq;
Usings!

2023-11-29 09:09 UTC, kalachck commented on CatNote.IntegrationTests/UserTests.cs
> +        };
The same about data creation

2023-11-29 09:22 UTC, MaliyOna commented on CatNote.BLL/Services/AchievementService.cs
> +            return;
for this part
![image](https://github.com/Finka95/CatNote/assets/76497091/da215a37-47f6-4b0d-a84f-7fc3a43e8db9)

2023-11-29 09:55 UTC, kalachck commented on CatNote.BLL/Services/AchievementService.cs
> +            return;
I mean, If it's null just return false or throw exception. How to understand what is going on whan front send a request and achive nothing from back

2023-11-29 13:15 UTC, kalachck requested changes

2023-11-29 13:15 UTC, kalachck commented on CatNote.IntegrationTests/UserTests.cs
> +        //Act
Resolve please unresolved comments

2023-12-05 07:45 UTC, kalachck approved these changes

2023-12-07 07:51 UTC, Finka95 approved these changes

2023-12-07 07:53 UTC, merged