Feature/nmd 452 set up a generic service
Finka95/CatNote pull request #8
Opened 2023-11-07 14:53 UTC by MaliyOna

2023-11-07 14:59 UTC, GodlyCat requested changes

2023-11-07 14:59 UTC, GodlyCat commented on CatNote.DAL/Repositories/Interfaces/IGenericRepository.cs
>  public interface IGenericRepository<TEntity> where TEntity : IBaseEntity
Move this folder to the root of project

2023-11-07 14:59 UTC, GodlyCat commented on CatNote.BLL/Services/IGenericService.cs
> +public interface IGenericService<TModel>
Create folder for Interfaces and move this folder to the root of the project

2023-11-07 14:59 UTC, GodlyCat commented on CatNote.DAL/Repositories/GenericRepository.cs
>          return result!;
Add AsNoTracking to GetById also

2023-11-07 14:59 UTC, GodlyCat commented on CatNote.BLL/Services/GenericService.cs
> +    public async Task Delete(int id, CancellationToken cancellationToken)
Convert to expression body

2023-11-08 08:49 UTC, Finka95 approved these changes

2023-11-08 09:16 UTC, GodlyCat approved these changes

2023-11-08 09:17 UTC, merged